### ISSUE TITLE
issue with PATH_OVERRIDE_SOONG

### ISSUE THREAD

**Issue by TheGlitchh** [Rebellion-Hub/vendor_Rebellion#5]
https://github.com/Rebellion-Hub/vendor_Rebellion/blob/9ea20dd3000a43c54046186a98fdbcfe0997f13f/config/BoardConfigKernel.mk#L134

In some cases it causes issues  :- https://del.dog/stohamebof.txt 

To fix this , refer to 

https://github.com/TheXPerienceProject/android_vendor_xperience/commit/5578c1958496638d83ccb30a92f066df6c5fccb3

**Comment by Abhat27** [comment]
Done!
